### ISSUE TITLE
Not receiving anything in my inbox nor spam folder

### ISSUE THREAD

**Issue by Wilfredforever** [MuhammadSheehab/FB-Phishing#9]
Hello and thanks for this. 
I do not receive emails. I've checked in my spam folder too and there's nothing. 
I tried it by entering my credentials. 
Apart from editing YOUR_EMAIL_ADDRESS in do_action.php do I need to edit anything else to get email? 
I'm new to this. Sorry.

**Comment by DjPrinceRaj** [comment]
Yeah It's Not Working For Me.

**Comment by cybercorps101** [comment]
Nothing works here
